apiVersion: v2
name: airflow-wrapper
description: Helm chart that wraps the official Apache Airflow Helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: airflow
    version: 1.18.0
    repository: https://airflow.apache.org  
